// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-wardrobe.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase-client.ts
import { createClient } from "npm:@supabase/supabase-js@^2.101.1";
function supabaseForUser(ctx) {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-wardrobe.ts
var list_wardrobe_default = defineTool({
  name: "list_wardrobe",
  title: "Lister le dressing",
  description: "Liste les v\xEAtements du dressing MyStyl de l'utilisateur connect\xE9 (cat\xE9gorie, type, couleur, style, occasion, marque).",
  inputSchema: {
    category: z.string().optional().describe("Filtrer par cat\xE9gorie, ex: Hauts, Bas, Chaussures."),
    limit: z.number().int().optional().describe("Nombre maximum de pi\xE8ces \xE0 retourner (d\xE9faut 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("wardrobe").select("id, category, subcategory, type, color, pattern, texture, fit, length, season, style, occasion, brand, price, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(Math.min(limit ?? 100, 300));
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, items: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-outfits.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var list_outfits_default = defineTool2({
  name: "list_outfits",
  title: "Lister les tenues",
  description: "Liste les tenues enregistr\xE9es de l'utilisateur MyStyl connect\xE9, avec les ids des pi\xE8ces qui les composent.",
  inputSchema: {
    limit: z2.number().int().optional().describe("Nombre maximum de tenues \xE0 retourner (d\xE9faut 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("outfits").select("id, name, item_ids, liked, is_modified, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(Math.min(limit ?? 50, 200));
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { count: data?.length ?? 0, outfits: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-style-profile.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_style_profile_default = defineTool3({
  name: "get_style_profile",
  title: "Profil style",
  description: "R\xE9cup\xE8re le profil style MyStyl de l'utilisateur connect\xE9 : morphologie, silhouette, colorim\xE9trie, styles pr\xE9f\xE9r\xE9s, lifestyle, budget.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("profiles").select(
      "pseudo, silhouette, morphologie, taille, corpulence, styles, styles_semaine, styles_weekend, lifestyle, budget, brands, favorite_colors, colorimetry_season, streak_current, streak_longest"
    ).eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Aucun profil trouv\xE9." }] };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/add-wardrobe-item.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
var add_wardrobe_item_default = defineTool4({
  name: "add_wardrobe_item",
  title: "Ajouter une pi\xE8ce au dressing",
  description: "Ajoute une pi\xE8ce (sans photo) au dressing MyStyl de l'utilisateur connect\xE9.",
  inputSchema: {
    category: z3.string().describe("Cat\xE9gorie, ex: Hauts, Bas, Chaussures."),
    type: z3.string().describe("Type de pi\xE8ce, ex: T-shirt, Jean droit."),
    subcategory: z3.string().optional(),
    color: z3.array(z3.string()).optional().describe("Couleurs de la pi\xE8ce."),
    season: z3.array(z3.string()).optional(),
    style: z3.array(z3.string()).optional(),
    occasion: z3.array(z3.string()).optional(),
    brand: z3.string().optional(),
    price: z3.number().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non authentifi\xE9" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("wardrobe").insert({
      user_id: ctx.getUserId(),
      category: input.category,
      type: input.type,
      subcategory: input.subcategory ?? null,
      color: input.color ?? [],
      season: input.season ?? [],
      style: input.style ?? [],
      occasion: input.occasion ?? [],
      brand: input.brand ?? null,
      price: input.price ?? null
    }).select("id, category, type").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Pi\xE8ce ajout\xE9e : ${data.type} (${data.id})` }],
      structuredContent: { item: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tseermbuwyrzcrulhxba";
var mcp_default = defineMcp({
  name: "mystyl-mcp",
  title: "MyStyl",
  version: "0.1.0",
  instructions: "Outils MyStyl : acc\xE8de au dressing, aux tenues et au profil style de l'utilisateur connect\xE9. Utilise `list_wardrobe` pour voir les v\xEAtements, `list_outfits` pour les tenues enregistr\xE9es, `get_style_profile` pour la morphologie/colorim\xE9trie/styles, et `add_wardrobe_item` pour ajouter une pi\xE8ce.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_wardrobe_default, list_outfits_default, get_style_profile_default, add_wardrobe_item_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
