// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tseermbuwyrzcrulhxba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZWVybWJ1d3lyemNydWxoeGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NDQ0ODEsImV4cCI6MjA4ODEyMDQ4MX0.L0sQO098BZpfV6qsplfDexGk6VtPBzCXG5qYLC9vHVc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});